{% set version = "0.9.2" %}
{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail" %}

package:
  name: pyproject-fmt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt/pyproject_fmt-{{ version }}.tar.gz
  sha256: a0c73df74ec0d95ddc04ecc4b836d247f1666656f583157ba6f141a46448adda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  entry_points:
    - pyproject-fmt = pyproject_fmt.__main__:run

requirements:
  host:
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - packaging >=23
    - tomlkit >=0.11.6
    - typing_extensions >=4.4

test:
  source_files:
    - tests
  imports:
    - pyproject_fmt
  commands:
    - pip check
    - pyproject-fmt --help
    - {{ pytest_args }} --cov-fail-under=99  # [not win]
    # fails with `FileNotFoundError``
    - {{ pytest_args }} -k "not test_help_invocation_as_script"  # [win]
  requires:
    - pip
    - pytest >=7.2
    - pytest-cov >=4
    - pytest-mock >=3.10

about:
  home: https://pypi.org/project/pyproject-fmt
  summary: Format your pyproject.toml file
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pyproject-fmt.readthedocs.io
  dev_url: https://github.com/tox-dev/pyproject-fmt
  description: |
    Apply a consistent format to your `pyproject.toml` file with comment support.

extra:
  recipe-maintainers:
    - bollwyvl
