{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k \"not classifier_gt_tox\"" %}
{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k \"not classifier_gt_tox\"" %}
{% set version = "0.12.1" %}

package:
  name: pyproject-fmt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt/pyproject_fmt-{{ version }}.tar.gz
  sha256: 01cd68477e87640944ece982d7bd1e14d006576041c8a8a65d4392660693bec2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  entry_points:
    - pyproject-fmt = pyproject_fmt.__main__:run

requirements:
  host:
    - hatch-vcs >=0.3
    - hatchling >=1.14.1
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - natsort >=8.3.1
    - packaging >=23.1
    - tomlkit >=0.11.8
    - typing_extensions >=4.5

test:
  source_files:
    - tests
  imports:
    - pyproject_fmt
  commands:
    - pip check
    - mypy -p pyproject_fmt
    - pyproject-fmt --help
    - {{ pytest_args }} --cov-fail-under=92  # [not win]
    # fails with `FileNotFoundError``
    - {{ pytest_args }} -k "not test_help_invocation_as_script"  # [win]
  requires:
    - mypy
    - pip
    - pytest >=7.2
    - pytest-cov >=4
    - pytest-mock >=3.10

about:
  home: https://pypi.org/project/pyproject-fmt
  summary: Format your pyproject.toml file
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pyproject-fmt.readthedocs.io
  dev_url: https://github.com/tox-dev/pyproject-fmt
  description: |
    Apply a consistent format to your `pyproject.toml` file with comment support.

extra:
  recipe-maintainers:
    - bollwyvl
